import "./globals.css";
import Layout from '@/components/Layout.js'
import AccountDataProvider from "@/store/accountData";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <AccountDataProvider>
        
        <Layout>
        
        {children}
        </Layout>
        
        </AccountDataProvider>
        </body>
    </html>
  );
}
